### PR TITLE
fix(npm): Change NPM rename method

### PR DESCRIPTION
**Pull request by satblip**
https://github.com/npm/npm/issues/9863

### CODE REVIEW

**Comment by SagaStalin** [comment]
<KGB>9fbde522c14417891f6d5884f4f5566fba5e0a4e
>no message

Status must start with one of the followings:
*doc, feat, fix, perf, refactor, revert, style, test*
Conform status to `<type>(<scope>): <subject>` pattern

**Comment by SagaStalin** [comment]
<KGB>5ca3902c16c7f97069074315122068ab6d582cca
>no message

Status must start with one of the followings:
*doc, feat, fix, perf, refactor, revert, style, test*
Conform status to `<type>(<scope>): <subject>` pattern

**Comment by SagaStalin** [comment]
<KGB>634568088225a8965837d4eae09be2cd50cb482f
>no message

Status must start with one of the followings:
*doc, feat, fix, perf, refactor, revert, style, test*
Conform status to `<type>(<scope>): <subject>` pattern

**Comment by aborsu** [comment]
BAD!!!

**Pull request merged**
